# ----
# Site

title: "Magic: The Gathering API Documentation"
description: "Documentation for the Magic: The Gathering API at magicthegathering.io"
url: https://docs.magicthegathering.io
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api_v1:
    title: API (v1)
    position: 2
  advanced:
    title: Advanced Usage
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
